flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.0.0
- cpphs-1.20.2
- data-default-class-0.0.1
- proto-lens-0.1.0.2
- proto-lens-protoc-0.1.0.2
resolver: lts-7.0

# Allow our custom Setup.hs scripts to import Data.ProtoLens.Setup from the version of
# # `proto-lens-protoc` in stack's local DB.  This makes things simpler when developing
# # `proto-lens-proto` and `proto-lens-tests` at the same time.
# #
# # For more details, see:
# # http://docs.haskellstack.org/en/latest/yaml_configuration/#explicit-setup-deps
explicit-setup-deps:
  "*": true
